/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import model.doctor.DoctorLigeroDTO;
import model.paciente.PacienteDTO;
import raven.datetime.DatePicker;

/**
 *
 * @author luis-
 */
public class AgendarUnaCita extends javax.swing.JPanel {

    /**
     * Creates new form AgendarUnaCita
     */
    public AgendarUnaCita() {
        initComponents();
        this.datePicker.setCloseAfterSelected(true);
    }

    
    public void limpiarCampos() {
        this.txtPacienteNombre.setText("");
        this.txtPacienteCedula.setText("");
        this.txtDoctorNombre.setText("");
        this.cbEspecialidad.setSelectedIndex(0);
        this.cbServicios.setSelectedIndex(0);
        this.cbHorarios.setSelectedIndex(0);
        this.datePicker.clearSelectedDate();
    }
    
    public void activarDatePicker() {
        this.datePicker.setEnabled(true);
        this.jtxtDatePicker.setEnabled(true);
    }

    public void desactivarDatePicker() {
        this.datePicker.setEnabled(false);
        this.jtxtDatePicker.setEnabled(false);
    }

    
    /**
     * Muestra el nombre y cedula del paciente elegido desde el ElegirPacienteDialog
     *
     * @param paciente paciente seleccinado
     */
    public void mostrarPacienteElegido(PacienteDTO paciente) {
        if (paciente != null) {
            txtPacienteNombre.setText(paciente.getNombre());
            txtPacienteCedula.setText(paciente.getCedula());
            
        }
    }

    /**
     * Muestra el nombre del doctor elegido desde el ElegirDoctorDialog
     *
     * @param doctor doctor seleccionado
     */
    public void mostrarDoctorElegido(DoctorLigeroDTO doctor) {
        if (doctor != null) {
            txtDoctorNombre.setText(doctor.getNombre());
        }
    }

    public JComboBox getCbServicios() {
        return this.cbServicios;
    }

    public JComboBox getCbHorarios() {
        return this.cbHorarios;
    }

    public JComboBox getCbEspecialidad() {
        return this.cbEspecialidad;
    }

    public DatePicker getDatePicker() {
        return datePicker;
    }

    public JButton getBtnPacienteFiltrar() {
        return this.btnPacienteFiltrar;
    }

    public JButton getBtnDoctorFiltrar() {
        return this.btnDoctorFiltrar;
    }
    
    public JButton getBtnAgendarUnaCita() {
        return this.btnAgendar;
    }
    
    public JButton getBtnLimpiarFiltros() {
        return this.btnLimpiarFiltros;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePicker = new raven.datetime.DatePicker();
        pnlExterior = new view.component.RoundPanel();
        pnlInterior = new javax.swing.JPanel();
        cbHorarios = new javax.swing.JComboBox<>();
        lbHorarios = new javax.swing.JLabel();
        pnlDoctor = new javax.swing.JPanel();
        lbDoctorNombre = new javax.swing.JLabel();
        txtDoctorNombre = new javax.swing.JTextField();
        btnDoctorFiltrar = new view.component.RoundedGreenButtom();
        jtxtDatePicker = new javax.swing.JFormattedTextField();
        lbFecha = new javax.swing.JLabel();
        cbEspecialidad = new javax.swing.JComboBox<>();
        pnlPacientes1 = new javax.swing.JPanel();
        txtPacienteNombre = new javax.swing.JTextField();
        txtPacienteCedula = new javax.swing.JTextField();
        labelPacienteNombre = new javax.swing.JLabel();
        lbPacienteCedula = new javax.swing.JLabel();
        btnPacienteFiltrar = new view.component.RoundedGreenButtom();
        lbEspecialidad = new javax.swing.JLabel();
        cbServicios = new javax.swing.JComboBox<>();
        lblServicio = new javax.swing.JLabel();
        btnAgendar = new view.component.RoundedGreenButtom();
        btnLimpiarFiltros = new view.component.RoundedGreenButtom();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        datePicker.setEditor(jtxtDatePicker);

        pnlExterior.setBackground(new java.awt.Color(197, 255, 204));

        pnlInterior.setBackground(new java.awt.Color(197, 255, 204));
        pnlInterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbHorarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHorarios.setText("horarios:");
        lbHorarios.setPreferredSize(new java.awt.Dimension(62, 30));

        pnlDoctor.setBackground(new java.awt.Color(197, 255, 204));
        pnlDoctor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Doctor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 14))); // NOI18N

        lbDoctorNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbDoctorNombre.setText("Nombre:");

        btnDoctorFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-search-30.png"))); // NOI18N

        javax.swing.GroupLayout pnlDoctorLayout = new javax.swing.GroupLayout(pnlDoctor);
        pnlDoctor.setLayout(pnlDoctorLayout);
        pnlDoctorLayout.setHorizontalGroup(
            pnlDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDoctorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtDoctorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoctorFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDoctorLayout.setVerticalGroup(
            pnlDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoctorLayout.createSequentialGroup()
                .addGroup(pnlDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDoctorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDoctorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoctorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDoctorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDoctorFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lbFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbFecha.setText("Fecha:");

        pnlPacientes1.setBackground(new java.awt.Color(197, 255, 204));
        pnlPacientes1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 14))); // NOI18N

        labelPacienteNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPacienteNombre.setText("Nombre:");

        lbPacienteCedula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPacienteCedula.setText("Cedula:");

        btnPacienteFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-search-30.png"))); // NOI18N

        javax.swing.GroupLayout pnlPacientes1Layout = new javax.swing.GroupLayout(pnlPacientes1);
        pnlPacientes1.setLayout(pnlPacientes1Layout);
        pnlPacientes1Layout.setHorizontalGroup(
            pnlPacientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPacientes1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlPacientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPacienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPacienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlPacientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPacienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPacienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnPacienteFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlPacientes1Layout.setVerticalGroup(
            pnlPacientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacientes1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPacientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPacienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPacienteNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPacientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPacienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPacienteCedula))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPacientes1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPacienteFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        lbEspecialidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEspecialidad.setText("Especialidad:");

        lblServicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblServicio.setText("Servicio:");

        btnAgendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-calendar-plus-30.png"))); // NOI18N
        btnAgendar.setText("Agendar");

        btnLimpiarFiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-clear-30.png"))); // NOI18N
        btnLimpiarFiltros.setText("L.Filtros");

        javax.swing.GroupLayout pnlInteriorLayout = new javax.swing.GroupLayout(pnlInterior);
        pnlInterior.setLayout(pnlInteriorLayout);
        pnlInteriorLayout.setHorizontalGroup(
            pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInteriorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPacientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInteriorLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbEspecialidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInteriorLayout.createSequentialGroup()
                        .addGroup(pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInteriorLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblServicio)
                                    .addComponent(lbFecha)))
                            .addGroup(pnlInteriorLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lbHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbHorarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtDatePicker)
                                .addComponent(cbServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInteriorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnLimpiarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pnlInteriorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAgendar, btnLimpiarFiltros});

        pnlInteriorLayout.setVerticalGroup(
            pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInteriorLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(pnlPacientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(pnlInteriorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pnlDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pnlInteriorLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAgendar, btnLimpiarFiltros});

        javax.swing.GroupLayout pnlExteriorLayout = new javax.swing.GroupLayout(pnlExterior);
        pnlExterior.setLayout(pnlExteriorLayout);
        pnlExteriorLayout.setHorizontalGroup(
            pnlExteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExteriorLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(pnlInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pnlExteriorLayout.setVerticalGroup(
            pnlExteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExteriorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pnlInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agendar una cita");

        jSeparator3.setForeground(new java.awt.Color(0, 153, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(pnlExterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlExterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.component.RoundedGreenButtom btnAgendar;
    private view.component.RoundedGreenButtom btnDoctorFiltrar;
    private view.component.RoundedGreenButtom btnLimpiarFiltros;
    private view.component.RoundedGreenButtom btnPacienteFiltrar;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JComboBox<Object> cbHorarios;
    private javax.swing.JComboBox<String> cbServicios;
    private raven.datetime.DatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JFormattedTextField jtxtDatePicker;
    private javax.swing.JLabel labelPacienteNombre;
    private javax.swing.JLabel lbDoctorNombre;
    private javax.swing.JLabel lbEspecialidad;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbHorarios;
    private javax.swing.JLabel lbPacienteCedula;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JPanel pnlDoctor;
    private view.component.RoundPanel pnlExterior;
    private javax.swing.JPanel pnlInterior;
    private javax.swing.JPanel pnlPacientes1;
    private javax.swing.JTextField txtDoctorNombre;
    private javax.swing.JTextField txtPacienteCedula;
    private javax.swing.JTextField txtPacienteNombre;
    // End of variables declaration//GEN-END:variables
}
