package view;

import java.awt.Color;
import java.awt.Component;
import view.component.menu.Paneles;
import view.component.menu.event.EventMenu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luis-
 * Este dashboard tiene la propiedad undecorated activada, por lo que no se muestran sus bordes
 * 
 * Este es el siguiente view que viene despues del Login.
 * Este recibe un parametro llamado ROl que utilizara para llamar
 * a un inicializador espececifico del menu.
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard(String rol) { // cambiar el detalle del rol
        initComponents();
        setBackground(new Color(0, 0, 0, 0)); // hacemos transparente la ventana
       

        // La interfaz EventMenu fue creada unicamente para que podamos
        // definir un objeto anonimo que implemente su unico metodo. Lo
        // sobreescribimos para gregar la funcionalidad de cambiar de paneles en 
        // este dashboard.
        EventMenu event = new EventMenu() {
            @Override
            public void seleccionado(Paneles panel) {
                System.out.println(panel);

                switch (panel) {
                    case GESTOR_DE_CITAS:
                        mostrarPanel(new FormModelo());
                        break;
                }

            }
        };
        
        // Dependiendo del entregado, se inicializa el menu.
        switch (rol) {
            case "admin": menu1.initAdmin(event); break;
            case "doctor": menu1.initDoctor(event); break;
            case "secretaria": menu1.initSecretaria(event); break;
            default: throw new AssertionError();
        }
    
    
        // Debuggin Logs

        System.out.printf("%d , %d ", panelCambiante.getWidth(), panelCambiante.getHeight() );

        
        
        // Agregar en este comentario un menu predeterminado.
        //mostrarPanel(new FormModelo());
    }
    
    /**
     * Metodo usado para cambiar el panel mostrado por el Dashboard. 
     * @param comp El panel que va a mostrar ahora el dashboard.
     */
    private void mostrarPanel(Component comp) {
        panelCambiante.removeAll();
        panelCambiante.add(comp);
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new view.component.RoundPanel();
        panelCambiante = new javax.swing.JPanel();
        menu1 = new view.component.menu.Menu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1244, 708));

        panelBackground.setBackground(new java.awt.Color(204, 204, 255));

        panelCambiante.setOpaque(false);
        panelCambiante.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(panelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(panelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.component.menu.Menu menu1;
    private view.component.RoundPanel panelBackground;
    private javax.swing.JPanel panelCambiante;
    // End of variables declaration//GEN-END:variables
}
