/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import view.component.table.TableHeaderAlignment;
import view.component.RoundedGreenButtom;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Component;
import java.time.LocalDate;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.paciente.Paciente;
import raven.datetime.DatePicker;

/**
 *
 * @author luis-
 */
public class Pacientes extends javax.swing.JPanel {

    /**
     * Creates new form Pacientes
     */
    public Pacientes() {
        initComponents();
        init();
        entrarEstadoDeGuardado();
    }

    /**
     * Este metodo se encarga de inicializar el estilo que utiliza la tabla
     * donde se muestran los pacientes. Para modificar estos estilos se
     * utiliza la libreria FlatJaf.
     * @see #FlatClientProperties
     */
    private void init() {
        tabla.getTableHeader().putClientProperty(FlatClientProperties.STYLE, ""
                + "height: 30;"
                + "hoverBackground:null;"
                + "pressedBackground:null;"
                + "separatorColor:$TableHeader.background;" // linea separadora de los headers
                + "font:bold;");

        tabla.putClientProperty(FlatClientProperties.STYLE, ""
                + "rowHeight:30;"
                + "showHorizontalLines:true;"
                + "intercellSpacing:0,1;" // muestra la separacion de las filas en un select multiple
                + "cellFocusColor:$TableHeader.hoverBackground;"
                + "selectionBackground:$TableHeader.hoverBackground;"
                + "selectionForeground:$Table.foreground;"); // cuando se cambia el hoverBackground las letras se vuelven blancas. lo arreglamos.

        scroll.getVerticalScrollBar().putClientProperty(FlatClientProperties.STYLE, ""
                + "trackArc:999;"
                + "trackInsets: 3,3,3,3;"
                + "thumbInsets: 3,3,3,3;"
                + "background:$Table.background;");

        tabla.getTableHeader().setDefaultRenderer(new TableHeaderAlignment(tabla));
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePicker1 = new raven.datetime.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlFiltrado = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        txtSeguro = new javax.swing.JTextField();
        lbSeguro = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lbCedula = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lbTelefono = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        LbFechaNacimiento = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lbDireccion = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        pnlContendorBotones = new javax.swing.JPanel();
        btnLimpiarFiltros = new view.component.RoundedGreenButtom();
        btnFiltrar = new view.component.RoundedGreenButtom();
        btnCrear = new view.component.RoundedGreenButtom();
        btnEditar = new view.component.RoundedGreenButtom();
        btnActualizar = new view.component.RoundedGreenButtom();
        btnCancelar = new view.component.RoundedGreenButtom();
        btnEliminar = new view.component.RoundedGreenButtom();
        ftxtDatePicker = new javax.swing.JFormattedTextField();
        scroll = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        datePicker1.setEditor(ftxtDatePicker);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Pacientes");

        jSeparator1.setForeground(new java.awt.Color(0, 153, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        pnlFiltrado.setBackground(new java.awt.Color(204, 255, 204));

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombre.setText("Nombre:");

        lbApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbApellido.setText("Apellidos:");

        lbSexo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSexo.setText("Sexo:");

        lbSeguro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSeguro.setText("Seguro");

        lbCedula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCedula.setText("Cedula:");

        lbTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTelefono.setText("Teléfono:");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEmail.setText("Email:");

        LbFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbFechaNacimiento.setText("Fecha de nacimiento:");

        lbDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbDireccion.setText("Dirección:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "M", "F" }));

        pnlContendorBotones.setBackground(new java.awt.Color(204, 255, 204));

        btnLimpiarFiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-clear-30.png"))); // NOI18N
        btnLimpiarFiltros.setText("L.Filtros");

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-search-30.png"))); // NOI18N
        btnFiltrar.setText("Filtrar");

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-save-30.png"))); // NOI18N
        btnCrear.setText("Crear");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-edit-30.png"))); // NOI18N
        btnEditar.setText("Editar");

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-uninstalling-updates-30.png"))); // NOI18N
        btnActualizar.setText("Actualizar");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-cancel-30.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-delete-30 (1).png"))); // NOI18N
        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout pnlContendorBotonesLayout = new javax.swing.GroupLayout(pnlContendorBotones);
        pnlContendorBotones.setLayout(pnlContendorBotonesLayout);
        pnlContendorBotonesLayout.setHorizontalGroup(
            pnlContendorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContendorBotonesLayout.createSequentialGroup()
                .addGroup(pnlContendorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContendorBotonesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlContendorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContendorBotonesLayout.createSequentialGroup()
                                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContendorBotonesLayout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContendorBotonesLayout.createSequentialGroup()
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlContendorBotonesLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlContendorBotonesLayout.setVerticalGroup(
            pnlContendorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContendorBotonesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlContendorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContendorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContendorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFiltradoLayout = new javax.swing.GroupLayout(pnlFiltrado);
        pnlFiltrado.setLayout(pnlFiltradoLayout);
        pnlFiltradoLayout.setHorizontalGroup(
            pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlFiltradoLayout.createSequentialGroup()
                        .addComponent(lbDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion))
                    .addGroup(pnlFiltradoLayout.createSequentialGroup()
                        .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(cbSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtSeguro))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFiltradoLayout.createSequentialGroup()
                                .addComponent(LbFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlFiltradoLayout.createSequentialGroup()
                                    .addComponent(lbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlFiltradoLayout.createSequentialGroup()
                                    .addComponent(lbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlFiltradoLayout.createSequentialGroup()
                                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(50, 50, 50)
                .addComponent(pnlContendorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnlFiltradoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelNombre, lbApellido, lbCedula, lbDireccion, lbEmail, lbSeguro, lbSexo, lbTelefono});

        pnlFiltradoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbSexo, ftxtDatePicker, txtApellido, txtCedula, txtEmail, txtNombre, txtTelefono});

        pnlFiltradoLayout.setVerticalGroup(
            pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSexo)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSeguro)
                    .addComponent(txtSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbFechaNacimiento)
                    .addComponent(ftxtDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFiltradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(pnlContendorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlFiltradoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbSexo, txtApellido});

        pnlFiltradoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ftxtDatePicker, txtEmail});

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CEDULA", "NOMBRE", "APELLIDOS", "SEXO", "SEGURO", "EMAIL", "TELEFONO", "F. NACIMIENTO", "DIRECCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroll.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(3).setPreferredWidth(30);
            tabla.getColumnModel().getColumn(4).setResizable(false);
            tabla.getColumnModel().getColumn(4).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(5).setResizable(false);
            tabla.getColumnModel().getColumn(5).setPreferredWidth(130);
            tabla.getColumnModel().getColumn(6).setResizable(false);
            tabla.getColumnModel().getColumn(6).setPreferredWidth(60);
            tabla.getColumnModel().getColumn(7).setResizable(false);
            tabla.getColumnModel().getColumn(7).setPreferredWidth(60);
            tabla.getColumnModel().getColumn(8).setResizable(false);
            tabla.getColumnModel().getColumn(8).setPreferredWidth(130);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFiltrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scroll))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(pnlFiltrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //Quizas una forma algo inconveniente. 
    
    /**
     * Recorre todos los componentes del pnlFiltrado, para verificar que los campos
     * no esten vacios.
     * @return <code>true</code> si los campos no estan vacios, de lo contrario <code>false</code>
     */
    public boolean validarCampos() {
        for (Component comp : pnlFiltrado.getComponents()) {
            if (comp instanceof JTextField textField) {
                if (textField.getText().trim().isEmpty()) {
                    textField.requestFocusInWindow();
                    JOptionPane.showMessageDialog(this, "Los campos deben de estar llenos!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    return false;
                } else if (comp instanceof JComboBox cb) {
                    if (((String) cb.getModel().getSelectedItem()).trim().isEmpty()) { //hacemos un typeCast a String del contenido del ComboBox
                        cb.requestFocusInWindow();
                        JOptionPane.showMessageDialog(this, "Los campos deben de estar llenos!", "Error", JOptionPane.INFORMATION_MESSAGE);
                        return false;
                    }
                } else if (comp instanceof JFormattedTextField ftxt) { // esta forma de validar el JFormattedtextfield es Unica del componente DatePicker. 
                    LocalDate fecha = datePicker1.getSelectedDate();
                    if (fecha == null) {
                        ftxt.requestFocusInWindow();
                        JOptionPane.showMessageDialog(this, "Los campos deben de estar llenos!", "Error", JOptionPane.INFORMATION_MESSAGE);
                        return false;
                    }
                }

            }
        }
        return true;
    }
    
    /**
     * Limpia todos los campos del panel de Pacientes
     */
    public void limpiarCampos() {
        txtNombre.setText("");
        txtApellido.setText("");
        cbSexo.setSelectedIndex(0); // Seleciona la opcion en blanco
        txtSeguro.setText("");
        txtDireccion.setText("");
        txtCedula.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        datePicker1.clearSelectedDate();
       
    }
    
    //Con tal de que el filtro de esta vista funcione, se convierten en null
    //los campos que el usuario dejo vacio. Por ello primero verificamos los campos.
    
    /**
     * Obtiene todos los datos del formulario del panel Pacientes
     * @return objeto <code>Paciente</code> con todos los datos cargados en sus atributos
     * @see #Pacientes() 
     */
    public Paciente obtenerDatos() {
        Paciente p = new Paciente();
        String nombre = (txtNombre.getText().trim().isEmpty()) ? null : txtNombre.getText().trim();
        String apellido = (txtApellido.getText().trim().isEmpty()) ? null : txtApellido.getText().trim();
        String cedula = (txtCedula.getText().trim().isEmpty()) ? null : txtCedula.getText().trim();

        String sexo = ((String) cbSexo.getModel().getSelectedItem());
        sexo = (sexo.trim().isEmpty()) ? null : sexo;

        String email = (txtEmail.getText().trim().isEmpty()) ? null : txtEmail.getText().trim();
        String telefono = (txtTelefono.getText().trim().isEmpty()) ? null : txtTelefono.getText().trim();
        String direccion = (txtDireccion.getText().trim().isEmpty()) ? null : txtDireccion.getText().trim();
        String seguro = (txtSeguro.getText().trim().isEmpty()) ? null : txtSeguro.getText().trim();

        p.setNombre(nombre);
        p.setApellido(apellido);
        p.setCedula(cedula);
        p.setSexo(sexo);
        p.setEmail(email);
        p.setTelefono(telefono);
        p.setDireccion(direccion);
        p.setSeguro(seguro);
        LocalDate fecha = datePicker1.getSelectedDate(); // Si no hay una fecha seleccioanda, DatePicker retorna null por si solo.
        p.setFechaNacimiento(fecha);
        return p;
    }
    
    /**
     * Modifica el estado de los botones para que solamente se pueda
     * Filtrar, limpiar los filtros o crear un nuevo paciente.
     * Se activa de nuevo la edicion del txtCedula.
     */
    public void entrarEstadoDeGuardado() {
        this.btnFiltrar.setEnabled(true);
        this.btnLimpiarFiltros.setEnabled(true);
        this.btnCrear.setEnabled(true);
        this.btnActualizar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);

        this.txtCedula.setEditable(true);
    }
    
    /**
     * modifica el estado de los botones para que solamente se pueda
     * editar, eliminar los datos de los pacientes o cancelar la accion
     */
    public void entrarEstadoDePreEdicion() {
        this.btnFiltrar.setEnabled(false);
        this.btnLimpiarFiltros.setEnabled(false);
        this.btnCrear.setEnabled(false);
        this.btnActualizar.setEnabled(false);
        this.btnCancelar.setEnabled(true);
        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
    }
    
    /**
     * Modifica el estado de los botones para que solamente se
     * pueda actualizar los datos del paciente o cancelar la accion.
     * Se desactiva la edicion del txtCedula para evitar problemas en el proceso
     * de actualizacion.
     */
    public void entrarEstadoDeEdicion() {
        this.btnFiltrar.setEnabled(false);
        this.btnLimpiarFiltros.setEnabled(false);
        this.btnCrear.setEnabled(false);
        this.btnActualizar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);

        this.txtCedula.setEditable(false);
    }

    /**
     * @return the tabla
     */
    public JTable getTabla() {
        return this.tabla;
    }

    /**
     * @return the btnLimpiarFiltros
     */
    public JButton getBtnLimpiarFiltros() {
        return this.btnLimpiarFiltros;
    }

    /**
     * @return the btnCrear
     */
    public JButton getBtnCrear() {
        return this.btnCrear;
    }

    /**
     * @return the btnEditar
     */
    public JButton getBtnEditar() {
        return this.btnEditar;
    }

    /**
     * @return the btnCancelar
     */
    public JButton getBtnCancelar() {
        return this.btnCancelar;
    }

    /**
     * @return the btnActualizar
     */
    public JButton getBtnActualizar() {
        return this.btnActualizar;
    }

    /**
     * @return the btnFiltrar
     */
    public JButton getBtnFiltrar() {
        return this.btnFiltrar;
    }

    /**
     * @return the btnEliminar
     */
    public JButton getBtnEliminar() {
        return this.btnEliminar;
    }

    /**
     * @return the datePicker
     */
    public DatePicker getDatePicker() { // esta es una forma unica de como editar el JformatedTexField de la fecha.
        return datePicker1;
    }

    /**
     * @return the txtApellido
     */
    public javax.swing.JTextField getTxtApellido() {
        return txtApellido;
    }

    /**
     * @return the txtCedula
     */
    public javax.swing.JTextField getTxtCedula() {
        return txtCedula;
    }

    /**
     * @return the txtDireccion
     */
    public javax.swing.JTextField getTxtDireccion() {
        return txtDireccion;
    }

    /**
     * @return the txtEmail
     */
    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }

    /**
     * @return the txtNombre
     */
    public javax.swing.JTextField getTxtNombre() {
        return txtNombre;
    }

    /**
     * @return the txtSeguro
     */
    public javax.swing.JTextField getTxtSeguro() {
        return txtSeguro;
    }

    /**
     * @return the txtTelefono
     */
    public javax.swing.JTextField getTxtTelefono() {
        return txtTelefono;
    }

    /**
     * @return the cbSexo
     */
    public javax.swing.JComboBox getCbSexo() {
        return cbSexo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbFechaNacimiento;
    private view.component.RoundedGreenButtom btnActualizar;
    private view.component.RoundedGreenButtom btnCancelar;
    private view.component.RoundedGreenButtom btnCrear;
    private view.component.RoundedGreenButtom btnEditar;
    private view.component.RoundedGreenButtom btnEliminar;
    private view.component.RoundedGreenButtom btnFiltrar;
    private view.component.RoundedGreenButtom btnLimpiarFiltros;
    private javax.swing.JComboBox<String> cbSexo;
    private raven.datetime.DatePicker datePicker1;
    private javax.swing.JFormattedTextField ftxtDatePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbSeguro;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JPanel pnlContendorBotones;
    private javax.swing.JPanel pnlFiltrado;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSeguro;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}