/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTable;
import model.especialidad.Especialidad;
import view.component.RoundedGreenButtom;

/**
 *
 * @author YELIANA
 */
public class PanelEspecialidades extends javax.swing.JPanel {

    /**
     * Creates new form PanelEspecialidades
     */
    public PanelEspecialidades() {
        initComponents();

        // Ocultamos el ID de los servicios. 
        // la idea es usar el ID para poder hacerle check o no al campo ¿ASOCIADO? de la tabla.
        this.tablaServiciosAsociados.getColumnModel().getColumn(0).setMinWidth(0);
        this.tablaServiciosAsociados.getColumnModel().getColumn(0).setPreferredWidth(0);
        this.tablaServiciosAsociados.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    public JList getJList() {
        return this.jlistaEspe;
    }

    public JButton getBtnAgregarEspecialidad() {
        return this.btnAgregarEspe;
    }

    public JButton getBtnEliminarEspecialidad() {
        return this.btneliminarEspe;
    }
    
    public JButton getBtnActualizarServiciosAsociados() {
        return this.btnActualizarServiciosAsociados;
    }

    public JTable getTableServiciosAsociados() {
        return this.tablaServiciosAsociados;
    }

    public boolean validarCampos() {
        return !(this.txtDescripcion.getText().isEmpty());
    }

    public void LimpiarCampos() {
        this.txtDescripcion.setText("");
    }

    public Especialidad ObtenerDatos() {
        if (validarCampos()) {
            String descripcion = this.txtDescripcion.getText();
            Especialidad e = new Especialidad();
            e.setDescripcion(descripcion);
            return e;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jRadioButton1 = new javax.swing.JRadioButton();
        btnFiltrar = new view.component.RoundedGreenButtom();
        btnCrear = new view.component.RoundedGreenButtom();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistaEspe = new javax.swing.JList<>();
        pnlServicioAsociado = new javax.swing.JPanel();
        btnActualizarServiciosAsociados = new view.component.RoundedGreenButtom();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaServiciosAsociados = new javax.swing.JTable();
        pnlEspecialidad = new javax.swing.JPanel();
        lbDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnAgregarEspe = new view.component.RoundedGreenButtom();
        btneliminarEspe = new view.component.RoundedGreenButtom();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-search-30.png"))); // NOI18N
        btnFiltrar.setText("Filtrar");

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-save-30.png"))); // NOI18N
        btnCrear.setText("Crear");

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Especialidades ");

        jSeparator1.setForeground(new java.awt.Color(0, 153, 0));

        jScrollPane1.setViewportView(jlistaEspe);

        pnlServicioAsociado.setBackground(new java.awt.Color(204, 255, 204));
        pnlServicioAsociado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnActualizarServiciosAsociados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-uninstalling-updates-30.png"))); // NOI18N
        btnActualizarServiciosAsociados.setText("ACTUALIZAR");
        btnActualizarServiciosAsociados.setFocusCycleRoot(true);

        tablaServiciosAsociados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVICIO", "¿ASOCIADO?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaServiciosAsociados);
        if (tablaServiciosAsociados.getColumnModel().getColumnCount() > 0) {
            tablaServiciosAsociados.getColumnModel().getColumn(0).setResizable(false);
            tablaServiciosAsociados.getColumnModel().getColumn(1).setResizable(false);
            tablaServiciosAsociados.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pnlServicioAsociadoLayout = new javax.swing.GroupLayout(pnlServicioAsociado);
        pnlServicioAsociado.setLayout(pnlServicioAsociadoLayout);
        pnlServicioAsociadoLayout.setHorizontalGroup(
            pnlServicioAsociadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicioAsociadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarServiciosAsociados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        pnlServicioAsociadoLayout.setVerticalGroup(
            pnlServicioAsociadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicioAsociadoLayout.createSequentialGroup()
                .addGroup(pnlServicioAsociadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServicioAsociadoLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnActualizarServiciosAsociados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlServicioAsociadoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEspecialidad.setBackground(new java.awt.Color(204, 255, 204));
        pnlEspecialidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbDescripcion.setText("Descripcion");

        btnAgregarEspe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-save-30.png"))); // NOI18N
        btnAgregarEspe.setText("GUARDAR");
        btnAgregarEspe.setToolTipText("");

        btneliminarEspe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/pacientes/icons/icons8-delete-30 (1).png"))); // NOI18N
        btneliminarEspe.setText("ELIMINAR");

        javax.swing.GroupLayout pnlEspecialidadLayout = new javax.swing.GroupLayout(pnlEspecialidad);
        pnlEspecialidad.setLayout(pnlEspecialidadLayout);
        pnlEspecialidadLayout.setHorizontalGroup(
            pnlEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEspecialidadLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btneliminarEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        pnlEspecialidadLayout.setVerticalGroup(
            pnlEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspecialidadLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnAgregarEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminarEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(pnlEspecialidadLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlServicioAsociado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(222, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(pnlServicioAsociado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.component.RoundedGreenButtom btnActualizarServiciosAsociados;
    private view.component.RoundedGreenButtom btnAgregarEspe;
    private view.component.RoundedGreenButtom btnCrear;
    private view.component.RoundedGreenButtom btnFiltrar;
    private view.component.RoundedGreenButtom btneliminarEspe;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<Object> jlistaEspe;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JPanel pnlEspecialidad;
    private javax.swing.JPanel pnlServicioAsociado;
    private javax.swing.JTable tablaServiciosAsociados;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
