/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import model.usuario.Rol;
import model.usuario.Usuario;
import java.io.File;
import java.io.IOException;
import view.component.menu.ImageAvatar;

/**
 *
 * @author user
 */

public class Usuarios extends javax.swing.JPanel {

    private byte[] imagenUsuario;
    private view.component.menu.ImageAvatar avatar;

    /**
     * Creates new form UsuariosN
     */
    public Usuarios() {
        initComponents();
        personalizarListUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlbTitulo = new javax.swing.JLabel();
        JspTitulo = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsuarios = new javax.swing.JList<>();
        JpFormulario = new javax.swing.JPanel();
        jlbNombre = new javax.swing.JLabel();
        jlbApellido = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JLabel();
        jlbContraseña = new javax.swing.JLabel();
        jlbRol = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        cbxRol = new javax.swing.JComboBox<>();
        btnCrearActualizar = new javax.swing.JButton();
        chbActivado = new javax.swing.JCheckBox();
        jlbTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnAgregarFoto = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        imageAvatar2 = new view.component.menu.ImageAvatar();
        JlTituloCreacion = new javax.swing.JLabel();
        JlTituloLista = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        JlbTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        JlbTitulo.setText("Usuarios");

        JspTitulo.setForeground(new java.awt.Color(0, 153, 0));

        listUsuarios.setBackground(new java.awt.Color(204, 255, 204));
        listUsuarios.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(listUsuarios);

        JpFormulario.setBackground(new java.awt.Color(204, 255, 204));
        JpFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbNombre.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlbNombre.setText("Nombre");
        JpFormulario.add(jlbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 20));

        jlbApellido.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlbApellido.setText("Apellido");
        JpFormulario.add(jlbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jlbEmail.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlbEmail.setText("Email");
        JpFormulario.add(jlbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jlbUsuario.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlbUsuario.setText("Usuario");
        JpFormulario.add(jlbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jlbContraseña.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlbContraseña.setText("Contraseña");
        JpFormulario.add(jlbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jlbRol.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlbRol.setText("Rol");
        JpFormulario.add(jlbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JpFormulario.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, 30));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JpFormulario.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JpFormulario.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, 30));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JpFormulario.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 30));

        cbxRol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxRol.setModel(new DefaultComboBoxModel<>(Rol.values()));
        JpFormulario.add(cbxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, 30));

        btnCrearActualizar.setBackground(new java.awt.Color(126, 209, 129));
        btnCrearActualizar.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        btnCrearActualizar.setText("CREAR");
        btnCrearActualizar.setBorder(null);
        JpFormulario.add(btnCrearActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 110, 30));

        chbActivado.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        chbActivado.setText("   Activado");
        JpFormulario.add(chbActivado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 180, 30));

        jlbTelefono.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jlbTelefono.setText("Teléfono");
        JpFormulario.add(jlbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, 20));

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JpFormulario.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 160, 30));

        btnAgregarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recursos/ImagenesUsuariosAgregar/boton-mas (1).png"))); // NOI18N
        btnAgregarFoto.setBorderPainted(false);
        btnAgregarFoto.setContentAreaFilled(false);
        btnAgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFotoActionPerformed(evt);
            }
        });
        JpFormulario.add(btnAgregarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JpFormulario.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 170, 30));

        imageAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/component/menu/icons/avatar/p2.png"))); // NOI18N
        JpFormulario.add(imageAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, 200));

        JlTituloCreacion.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        JlTituloCreacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlTituloCreacion.setText("Creación de Usuarios");

        JlTituloLista.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        JlTituloLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlTituloLista.setText("Lista de Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JspTitulo)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JlbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JlTituloLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JpFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JlTituloCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JlbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(JspTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlTituloLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlTituloCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JpFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg", "bmp"));

        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();

            try {
                imagenUsuario = java.nio.file.Files.readAllBytes(archivo.toPath());
                ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());
                this.imageAvatar2.setIcon(icono);

            } catch (IOException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar imagen");
            }
        }
    }

    private void personalizarListUsuarios() {
        listUsuarios.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                    boolean isSelected, boolean cellHasFocus) {
                JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Usuario) {
                    Usuario u = (Usuario) value;
                    String texto = "<html><b>" + u.getNombre() + " " + u.getApellido() + "</b><br>"
                            + "<span style='color:gray;'>" + u.getRol() + "</span></html>"; // Verde claro
                    label.setText(texto);
                }
                return label;
            }
        });
    }

    public boolean validarCampos() {
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "El campo 'Nombre' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (txtApellido.getText().trim().isEmpty()) {
            txtApellido.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "El campo 'Apellido' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (txtUsuario.getText().trim().isEmpty()) {
            txtUsuario.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "El campo 'Usuario' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (txtContraseña.getText().trim().isEmpty()) {
            txtContraseña.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "El campo 'Contraseña' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (txtEmail.getText().trim().isEmpty()) {
            txtEmail.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "El campo 'Email' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "El campo 'Teléfono' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (cbxRol.getSelectedItem() == null || cbxRol.getSelectedItem().toString().trim().isEmpty()) {
            cbxRol.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Rol.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    public void limpiarCampos() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        cbxRol.setSelectedIndex(0);
        chbActivado.setSelected(false);
        listUsuarios.clearSelection();
        // Limpiar la imagen
        imagenUsuario = null;

    }

    public Usuario obtenerDatos() {
        Usuario u = new Usuario();

        u.setNombre(txtNombre.getText().trim());
        u.setApellido(txtApellido.getText().trim());
        u.setUsuario(txtUsuario.getText().trim());
        u.setContrasena(txtContraseña.getText().trim());
        u.setEmail(txtEmail.getText().trim());
        u.setTelefono(txtTelefono.getText().trim());
        u.setActivo(chbActivado.isSelected());

        Rol rolSeleccionado = (Rol) cbxRol.getSelectedItem();
        u.setRol(rolSeleccionado);

        // Asignar la imagen cargada al objeto Usuario
        u.setImagen(imagenUsuario);
        return u;
    }

    // Getters y Setters para los campos del formulario
    public javax.swing.JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(javax.swing.JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public javax.swing.JTextField getTxtApellido() {
        return txtApellido;
    }

    public void setTxtApellido(javax.swing.JTextField txtApellido) {
        this.txtApellido = txtApellido;
    }

    public javax.swing.JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(javax.swing.JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

    public javax.swing.JPasswordField getTxtContraseña() {
        return txtContraseña;
    }

    public void setTxtContraseña(javax.swing.JPasswordField txtContraseña) {
        this.txtContraseña = txtContraseña;
    }

    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(javax.swing.JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public javax.swing.JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(javax.swing.JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public javax.swing.JComboBox<Rol> getCbxRol() {
        return cbxRol;
    }

    public void setCbxRol(javax.swing.JComboBox<Rol> cbxRol) {
        this.cbxRol = cbxRol;
    }

    public javax.swing.JCheckBox getChbActivado() {
        return chbActivado;
    }

    public void setChbActivado(javax.swing.JCheckBox chbActivado) {
        this.chbActivado = chbActivado;
    }

    public javax.swing.JList<Usuario> getListUsuarios() {
        return listUsuarios;
    }

    public void setListUsuarios(javax.swing.JList<Usuario> listUsuarios) {
        this.listUsuarios = listUsuarios;
    }

    public javax.swing.JButton getBtnCrearActualizar() {
        return btnCrearActualizar;
    }

    public void setBtnCrearActualizar(javax.swing.JButton btnCrearActualizar) {
        this.btnCrearActualizar = btnCrearActualizar;
    }

    public javax.swing.JButton getBtnAgregarFoto() {
        return btnAgregarFoto;
    }

    public void setBtnAgregarFoto(javax.swing.JButton btnAgregarFoto) {
        this.btnAgregarFoto = btnAgregarFoto;
    }

    public ImageAvatar getAvatar() {
        return this.imageAvatar2;
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlTituloCreacion;
    private javax.swing.JLabel JlTituloLista;
    private javax.swing.JLabel JlbTitulo;
    private javax.swing.JPanel JpFormulario;
    private javax.swing.JSeparator JspTitulo;
    private javax.swing.JButton btnAgregarFoto;
    private javax.swing.JButton btnCrearActualizar;
    private javax.swing.JComboBox<Rol> cbxRol;
    private javax.swing.JCheckBox chbActivado;
    private view.component.menu.ImageAvatar imageAvatar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbApellido;
    private javax.swing.JLabel jlbContraseña;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbRol;
    private javax.swing.JLabel jlbTelefono;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JList<Usuario> listUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
