/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component;

import java.awt.Container;
import javax.swing.SwingUtilities;

/**
 *
 * @author luis-
 */
public class ContentBlock extends javax.swing.JPanel {

    /**
     * Creates new form ContentBlock
     */
    public ContentBlock() {
        initComponents();
        centerThisContainer();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void centerThisContainer() {
        SwingUtilities.invokeLater(() -> { // Para evitar que me explote el programa. Que se centre la GUI cuando todo este cargado
            Container parentContainer = this.getParent();
            int parentWidth = parentContainer.getWidth();
            int parentHeight = parentContainer.getHeight();
            int childWidth = this.getWidth();
            int childHeight = this.getHeight();
            int newX = (parentWidth - childWidth) / 2;
            int newY = (parentHeight - childHeight) / 2;
            this.setBounds(newX, newY, childWidth, childHeight);
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
